name: test

on: [push, pull_request]

jobs:
  test:
    name: test - node ${{matrix.node}} - ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12.x, 13.x, 14.x, 15.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup node ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - name: Get npm cache directory
        id: npmcachedir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ${{steps.npmcachedir.outputs.dir}}
          key: ${{runner.os}}-npm-${{hashFiles('**/package.json')}}
          restore-keys: ${{runner.os}}-npm-

      - run: npm install
      - run: npm run test